apiVersion: v1
kind: ReplicationController
metadata:
  name: helloflask
  labels:
    name: helloflask
spec:
  replicas: 1
  selector:
    name: helloflask
  template:
    metadata:
      labels:
        name: helloflask
    spec:
      containers:
        - name: helloflask
          image: $image
          ports:
            - name: flaskserver
              containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: REDIS_MASTER_PORT_6379_TCP_ADDR
              value: "$redis_master_host"
            - name: REDIS_MASTER_PORT_6379_TCP_PORT
              value: "$redis_master_port"
            - name: REDIS_SLAVE_PORT_6379_TCP_ADDR
              value: "$redis_slave_host"
            - name: REDIS_SLAVE_PORT_6379_TCP_PORT
              value: "$redis_slave_port"
