apiVersion: v1
kind: Service
metadata:
  name: helloflask-svc
  labels:
    name: helloflask-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: helloflask
